before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags: -trimpath
    ldflags: '-s -w -extldflags "-static"'
    main: ./cmd/
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - "quay.io/tinkerbell/ipxedust:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "quay.io/tinkerbell/ipxedust:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
  - image_templates:
      - "quay.io/tinkerbell/ipxedust:{{ .Version }}-arm"
    use: buildx
    goarch: arm
    goarm: "6"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
docker_manifests:
  - name_template: quay.io/tinkerbell/ipxedust:{{ .Version }}
    image_templates:
      - quay.io/tinkerbell/ipxedust:{{ .Version }}-amd64
      - quay.io/tinkerbell/ipxedust:{{ .Version }}-arm64
      - quay.io/tinkerbell/ipxedust:{{ .Version }}-arm
